package runner

import (
	"os"
	"path/filepath"
	"testing"
)

// Changing a setting by appending a line is the obvious thing to do, and it
// leaves the file with the key in it twice. The server keeps the first, so
// anything else reading the same file has to keep the first too.
//
// This cost real time once: a port appended to the end never took effect,
// while status read it back and reported it as though it had, so the file
// looked right and the server was doing something else.
func TestDuplicateKeysReadTheSameWayTheServerDoes(t *testing.T) {
	dir := t.TempDir()
	install := Install{Dir: dir, EnvPath: filepath.Join(dir, ".env")}

	contents := "" +
		"# generated by localdrive setup\n" +
		"LD_PORT=7443\n" +
		"LD_DOMAIN=drive.example.com\n" +
		"LISTEN_ADDR=:7443\n" +
		"\n" +
		"LD_TLS=off\n" +
		"LISTEN_ADDR=:80\n"
	if err := os.WriteFile(install.EnvPath, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}

	env := install.ReadEnv()
	if got := env["LISTEN_ADDR"]; got != ":7443" {
		t.Errorf("LISTEN_ADDR read as %q, but the server binds the first one, :7443", got)
	}
	// a key appearing once is unaffected by any of this
	if got := env["LD_TLS"]; got != "off" {
		t.Errorf("LD_TLS read as %q, want off", got)
	}
	if got := install.Port(); got != 7443 {
		t.Errorf("Port() = %d, want 7443", got)
	}
}

// Turning the certificate off has to be visible in what the addresses claim,
// or status offers an https address that nothing is listening for.
func TestAddressesFollowTLSBeingTurnedOff(t *testing.T) {
	if kind := TLSKindFor("drive.example.com", "off", false); kind != TLSNone {
		t.Fatalf("LD_TLS=off still reported kind %v", kind)
	}
	for _, address := range ServerAddresses("drive.example.com", 7443, TLSNone) {
		if len(address) >= 6 && address[:6] == "https:" {
			t.Errorf("https address %q offered with the certificate turned off", address)
		}
	}
}
