package runner

import (
	"fmt"
	"os"
	"strings"
)

// The proxy configuration and the compose file are generated, not shipped with
// blanks to fill in. A committed template with a placeholder domain in it is
// something a person has to notice and edit, and the point of this tool
// is that they should not have to.

// ProxyConfig is what the Caddyfile is rendered from.
type ProxyConfig struct {
	Port int

	// Domain is empty for the ordinary case: a server reached at an address on
	// the local network, with no domain and no certificate authority that
	// would issue one for it.
	Domain string

	// TLSEmail is only used when a domain is set, for the renewal notices a
	// public certificate authority sends. Empty means Caddy does not register
	// one, which is fine.
	TLSEmail string
}

// UsesPublicTLS reports whether this install can get a real certificate.
func (p ProxyConfig) UsesPublicTLS() bool { return strings.TrimSpace(p.Domain) != "" }

// SiteAddress is what Caddy binds and answers for.
func (p ProxyConfig) SiteAddress() string {
	if p.UsesPublicTLS() {
		return fmt.Sprintf("%s:%d", strings.TrimSpace(p.Domain), p.Port)
	}
	// no domain, so it answers on whatever address it was reached at. keep the
	// http:// prefix: without a scheme caddy enables automatic https and signs
	// its own certificate for the ip. browsers warn on every visit and the
	// app's http client rejects it, which looks like the server being down.
	return fmt.Sprintf("http://:%d", p.Port)
}

// BaseURL is the absolute address share links and invite links are built from.
func (p ProxyConfig) BaseURL() string {
	if p.UsesPublicTLS() {
		if p.Port == 443 {
			return "https://" + strings.TrimSpace(p.Domain)
		}
		return fmt.Sprintf("https://%s:%d", strings.TrimSpace(p.Domain), p.Port)
	}
	// with no domain there is no single correct address, since the same server
	// is reachable at every address the machine has. the app fills this in
	// from whichever one it connected to.
	return ""
}

// RenderCaddyfile builds the proxy configuration for this install.
func RenderCaddyfile(cfg ProxyConfig) string {
	var b strings.Builder

	b.WriteString("# Generated by localdrive. Edit if you like; localdrive setup\n")
	b.WriteString("# will not overwrite it once it exists.\n\n")

	b.WriteString("{\n")
	b.WriteString("\tadmin off\n")
	if cfg.UsesPublicTLS() && strings.TrimSpace(cfg.TLSEmail) != "" {
		fmt.Fprintf(&b, "\temail %s\n", strings.TrimSpace(cfg.TLSEmail))
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "%s {\n", cfg.SiteAddress())

	if cfg.UsesPublicTLS() {
		b.WriteString("\t# a real domain, so a real certificate, renewed automatically\n")
	} else {
		b.WriteString("\t# plain http, because there is no domain here and no certificate\n")
		b.WriteString("\t# authority will issue for an ip address. traffic stays on your own\n")
		b.WriteString("\t# network. to encrypt it, point a domain at this machine and set\n")
		b.WriteString("\t# LD_DOMAIN in .env: caddy gets a real certificate on its own.\n")
	}

	b.WriteString(`
	encode zstd gzip

	# large uploads and downloads stream through rather than buffering
	request_body {
		max_size 0
	}

	handle /api/* {
		reverse_proxy server:` + fmt.Sprint(InternalPort) + ` {
			flush_interval -1
			transport http {
				read_timeout 0
				write_timeout 0
			}
		}
	}

	handle /s/* {
		reverse_proxy server:` + fmt.Sprint(InternalPort) + `
	}

	handle /healthz {
		reverse_proxy server:` + fmt.Sprint(InternalPort) + `
	}

	handle /metrics {
		# reachable from the local network only; open this up deliberately
		@external not remote_ip private_ranges
		respond @external 403
		reverse_proxy server:` + fmt.Sprint(InternalPort) + `
	}

	# the app's web build, with the fallback that makes a refresh or a pasted
	# link on a path like /files/abc123 work instead of 404ing
	handle {
		root * /srv/web
		try_files {path} /index.html
		file_server
	}

	header {
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
		Referrer-Policy no-referrer
		-Server
	}

	@immutable path *.js *.css *.woff2 *.png *.jpg *.svg
	header @immutable Cache-Control "public, max-age=31536000, immutable"

	@shell path /index.html /
	header @shell Cache-Control "no-cache"

	log {
		output stdout
		format console
	}
}
`)
	return b.String()
}

// RenderCompose builds the compose file for this install. The image is built
// from this repository, and every service runs the same binary in a different
// mode.
func RenderCompose(cfg ProxyConfig, dataDir, externalMounts string) string {
	return `# Generated by localdrive. Every service runs the same localdrive binary
# in a different mode; the privilege boundary is the container, not the file.

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      # a compose build is a build from source, so it reports "dev" unless you
      # say otherwise. set LD_VERSION to stamp a real one.
      args:
        VERSION: ${LD_VERSION:-dev}
    command: ["serve"]
    restart: unless-stopped
    # optional on purpose: with no .env at all the server generates its own
    # secrets on first start and writes them beside the database
    env_file:
      - path: .env
        required: false
    # these are paths inside the container, fixed by the volume mounts below.
    # pinned here rather than left to .env, because compose environment beats
    # env_file: that frees .env to hold real host paths for a bare
    # "localdrive serve", so the same file is correct in both modes.
    environment:
      LISTEN_ADDR: ":` + fmt.Sprint(InternalPort) + `"
      # caddy owns the certificate in this mode. Two acme clients asking for
      # the same domain race for the challenge and both lose, so the server
      # never asks for one of its own here.
      LD_TLS: "off"
      DB_PATH: /data/db/localdrive.sqlite
      LIBRARY_PATH: /data/library
      EXTERNAL_MOUNTS_PATH: /data/external
      MOUNT_HELPER_SOCKET: /run/localdrive/mount-helper.sock
      LAN_DISCOVERY_SOCKET: /run/localdrive-discovery/lan-discovery.sock
    volumes:
      - ${DATA_DIR:-./data}/db:/data/db
      - ${DATA_DIR:-./data}/library:/data/library
      - ${EXTERNAL_MOUNTS_HOST:-./data/external}:/data/external
      - mount_helper_socket:/run/localdrive
      - lan_discovery_socket:/run/localdrive-discovery
    read_only: true
    tmpfs:
      - /tmp:size=256m,mode=1777
    mem_limit: 512m
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "/localdrive", "healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # the only container with elevated host access. linux only; on a windows
  # host, leave this out and manage drives from windows itself.
  mount-helper:
    profiles: ["drives"]
    build:
      context: .
      dockerfile: Dockerfile
    command: ["mount-helper"]
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev:/dev
    security_opt:
      - apparmor:unconfined
    environment:
      MOUNT_HELPER_SOCKET: /run/localdrive/mount-helper.sock
      MOUNT_HELPER_SHARED_SECRET: ${MOUNT_HELPER_SHARED_SECRET:-}
      EXTERNAL_MOUNTS_PATH: /srv/localdrive/external
    volumes:
      - ${EXTERNAL_MOUNTS_HOST:-./data/external}:/srv/localdrive/external:rshared
      - mount_helper_socket:/run/localdrive
      # read only, and only so it can pick up the secret the server generated
      - ${DATA_DIR:-./data}/db:/data/db:ro
    mem_limit: 64m

  # host networking for mdns only, no library or database access
  lan-discovery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["lan-discovery"]
    restart: unless-stopped
    network_mode: host
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      LAN_DISCOVERY_SOCKET: /run/localdrive-discovery/lan-discovery.sock
      LAN_DISCOVERY_SHARED_SECRET: ${LAN_DISCOVERY_SHARED_SECRET:-}
      LD_PORT: ${LD_PORT:-` + fmt.Sprint(DefaultPort) + `}
    volumes:
      - lan_discovery_socket:/run/localdrive-discovery
      - ${DATA_DIR:-./data}/db:/data/db:ro
    mem_limit: 32m

  proxy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "${LD_PORT:-` + fmt.Sprint(DefaultPort) + `}:${LD_PORT:-` + fmt.Sprint(DefaultPort) + `}"
      - "${LD_PORT:-` + fmt.Sprint(DefaultPort) + `}:${LD_PORT:-` + fmt.Sprint(DefaultPort) + `}/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web:/srv/web:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      server:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:
  mount_helper_socket:
  lan_discovery_socket:
`
}

// writeIfAbsent writes a generated file, leaving anything already there alone,
// so a hand edit survives running setup again.
func writeIfAbsent(path, contents string) (bool, error) {
	if _, err := os.Stat(path); err == nil {
		return false, nil
	}
	return true, os.WriteFile(path, []byte(contents), 0o644)
}
