/*
  Generates src/lib/l10n.generated.ts from the Flutter client's arb files.

  The strings live in one place, localdrive/lib/l10n, and both clients read
  them from there. Copying them by hand would guarantee the two drift, and the
  Arabic would drift first because nobody reviewing a diff reads it.

  Run: node scripts/gen-l10n.mjs
*/
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const arbDir = join(here, "..", "..", "localdrive", "lib", "l10n");

const read = (locale) =>
  JSON.parse(readFileSync(join(arbDir, `app_${locale}.arb`), "utf8"));

const en = read("en");
const ar = read("ar");

const keys = Object.keys(en).filter((k) => !k.startsWith("@"));

/** {name} placeholders become template parameters. */
const paramsOf = (value) => [
  ...new Set([...String(value).matchAll(/\{(\w+)\}/g)].map((m) => m[1])),
];

const lines = [];
lines.push("// Generated by scripts/gen-l10n.mjs from localdrive/lib/l10n/*.arb.");
lines.push("// Do not edit by hand: change the arb files and run the script.");
lines.push("");
lines.push("export type Locale = \"en\" | \"ar\";");
lines.push("");

const entry = (dict) => {
  const out = [];
  for (const key of keys) {
    const raw = dict[key] ?? en[key];
    const params = paramsOf(raw);
    if (params.length === 0) {
      out.push(`  ${JSON.stringify(key)}: ${JSON.stringify(raw)},`);
    } else {
      const args = params.map((p) => `${p}: string | number`).join("; ");
      let body = JSON.stringify(raw);
      for (const p of params) {
        body = body.replace(new RegExp(`\\{${p}\\}`, "g"), `" + String(v.${p}) + "`);
      }
      out.push(`  ${JSON.stringify(key)}: (v: { ${args} }) => ${body},`);
    }
  }
  return out.join("\n");
};

lines.push("// values are not `as const`: Arabic has to satisfy the same shape, and");
lines.push("// narrowing every English string to its own literal type prevents that.");
lines.push("const en = {");
lines.push(entry(en));
lines.push("};");
lines.push("");
lines.push("const ar: typeof en = {");
lines.push(entry(ar));
lines.push("};");
lines.push("");
lines.push("export const strings = { en, ar };");
lines.push("export type Strings = typeof en;");
lines.push("");

mkdirSync(join(here, "..", "src", "lib"), { recursive: true });
writeFileSync(join(here, "..", "src", "lib", "l10n.generated.ts"), lines.join("\n"), "utf8");

console.log(`wrote ${keys.length} strings for en and ar`);
