import Image from "next/image";

import { Mark } from "@/components/brand/Mark";
import { site } from "@/lib/site";

/*
  The source for the social card.

  Not shipped to readers: it exists so the card can be regenerated by
  screenshotting this route at 1200 by 630 whenever the branding or the
  screenshot changes. Rendering it as a real page rather than composing it in
  an image library means it uses the same tokens, the same typeface and the
  same mark as everything else, so it cannot drift from the site.

  Regenerate with:
    npm start, then screenshot /og-preview at 1200x630 into public/og.png
*/
export const metadata = { robots: { index: false, follow: false } };

export default function OgPreview() {
  return (
    /*
      Fixed and over everything, so a screenshot of a 1200 by 630 viewport is
      exactly the card with none of the site's own navigation in it.
    */
    <div
      className="fixed inset-0 z-[100] flex flex-col justify-between overflow-hidden bg-base"
      style={{ width: 1200, height: 630 }}
    >
      {/* the product, bled off the right edge so it reads as a window into
          something larger rather than a shrunken screenshot floating in space */}
      <div className="absolute -right-24 top-24 w-[760px] overflow-hidden rounded-card border border-stroke">
        <Image
          src="/showcase/app/app-files-desktop.png"
          alt=""
          width={1440}
          height={900}
          className="w-full"
        />
      </div>

      {/* a flat scrim so the type stays readable over the screenshot. not a
          gradient: a single flat panel with a hard edge, which is what this
          design system allows */}
      <div className="absolute inset-y-0 left-0 w-[660px] bg-base" />

      <div className="relative px-14 pt-12">
        <div className="flex items-center gap-4">
          <Mark size={52} />
          <span className="text-[30px] font-bold tracking-[-0.02em]">
            {site.name}
          </span>
        </div>
      </div>

      <div className="relative max-w-[600px] px-14 pb-12">
        <h1 className="text-[56px] font-bold leading-[1.05] tracking-[-0.03em]">
          {site.tagline}
        </h1>
        <p className="mt-5 text-[20px] leading-[29px] text-fg-secondary">
          A private alternative to Google Drive that runs on hardware you own.
        </p>
        <div className="mt-7 flex items-center gap-3">
          <span className="rounded-pill bg-accent px-5 py-2 text-[17px] font-semibold">
            Self hosted
          </span>
          <span className="rounded-pill border border-stroke px-5 py-2 text-[17px] font-semibold text-fg-secondary">
            MIT licensed
          </span>
        </div>
      </div>
    </div>
  );
}
